### ISSUE TITLE
fails to install from the latest image - python version error?

### ISSUE THREAD

**Issue by alexgherman** [MycroftAI/enclosure-picroft#171]
**Describe the bug**

**To Reproduce**
1. Install the latest picroft image on a raspberry pi 4, 2Gb
2. seeing this error:
https://paste.debian.net/1287933
3. Tried to run dev-setup and getting the same error

Running `./start-mycroft.sh all` works fine, but `./start-mycroft.sh cli` fails with this:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/pi/mycroft-core/mycroft/__init__.py", line 17, in <module>
    from mycroft.api import Api
  File "/home/pi/mycroft-core/mycroft/api/__init__.py", line 22, in <module>
    from mycroft.configuration import Configuration
  File "/home/pi/mycroft-core/mycroft/configuration/__init__.py", line 15, in <module>
    from .config import Configuration, LocalConf, RemoteConf
  File "/home/pi/mycroft-core/mycroft/configuration/config.py", line 26, in <module>
    from mycroft.util.combo_lock import ComboLock
  File "/home/pi/mycroft-core/mycroft/util/__init__.py", line 24, in <module>
    from mycroft.util.format import nice_number
  File "/home/pi/mycroft-core/mycroft/util/format.py", line 34, in <module>
    from lingua_franca import get_default_loc
ImportError: cannot import name 'get_default_loc' from 'lingua_franca' (/home/pi/mycroft-core/.venv/lib/python3.7/site-packages/lingua_franca/__init__.py)
```

Looks like a python version mismatch but I might be wrong. Can anyone help? Thank you in advance.

**Comment by Diamantino-Op** [comment]
same here

**Comment by Diamantino-Op** [comment]
ok, fixed
Solution: clone the lingua_franca repo from github, navigate to lingua_franca in site-packages and delete every file, then put the content of the lingua_franca from the downloaded content inside the folder on the picroft, and done.
